export const ORIGINAL_HEADER = 'x-robber-origin-url';
export const CONFIG_STORAGE_KEY = 'CUSTOM_ROBBER_CONFIG';
export const DOMAINS_STORAGE_KEY = 'CUSTOM_ROBBER_DOMAINS';
export const MESSAGE_BEGIN_ROBBER = 'MESSAGE_BEGIN_ROBBER';
export const MESSAGE_MODIFY_CORS = 'MODIFY_CORS';
export const SPY_CUSTOM_EVENT = 'SPY_CUSTOM_EVENT';
